### PR TITLE
Adding instantiate method to buildconfigs

### PR DESCRIPTION
**Pull request by tavogel**
Also added missing test coverage for instantiateBinary...

### CODE REVIEW

**Comment by tavogel** [comment]
Current usage example:

```
    options.body = JSON.stringify({
      kind: 'BuildRequest',
      apiVersion: 'v1',
      metadata: {
        name: buildconfigname
      },
      env: Object.keys(parameters).map(name => ({
        name,
        value: parameters[name]
      })),
      triggeredBy: [{
        message: 'Bla-bla-bla'
      }]
    })

    const response = await openshift.buildconfigs.instantiate(buildconfigname, options)
```

**Comment by lholmquist** [comment]
@tavogel looks like there are some linting errors on that last commit.

What does the initiate method do.  i'm to lazy to look it up :)

**Comment by tavogel** [comment]
Woops... fixed

Initiate method tells a BuildConfig to run (Jenkins Pipeline or Docker Build, etc)

**Comment by lholmquist** [comment]
just published as 1.1.0

**Pull request merged**
