### PR TITLE
PVC & Events methods

### PR DESCRIPTION
**Pull request by faust64**
couple methods I've been missing using that library.

### CODE REVIEW

**Comment by faust64** [comment]
--if I understand properly, tests are failing due to some vulnerable dependency being spotted by nsp
I did notice this setting it up over here, it shouldn't prevent tests from running, ...
AFAIU, a fix for this nsp error would be on its way ( see: joyent/node-http-signature#68 )

**Comment by lholmquist** [comment]
let me fix that security issue and i'll let you know when to do a quick rebase

**Comment by faust64** [comment]
perfect, thanks!

**Comment by lholmquist** [comment]
@faust64 looks like your history got a little messy.

**Comment by lholmquist** [comment]
@faust64 I cleaned up the history a bit and yours bits landed via this pr #68 

Thanks!!

**Comment by lholmquist** [comment]
Now in npm as 1.2.0

**Pull request closed without merging**
